name: New Product Form
description: form New Product
title: "New - "
body:
- type: markdown
  attributes:
    value: "## Welcome to new product!"
- type: input
  id: product_name
  attributes:
    label: Product Name
    description: "name of product"
    placeholder: "name of product"
  validations:
    required: true
- type: checkboxes
  id: cbb
  attributes:
    label: Task
    description: You may select more than one.
    options:
      - label: APP 1
        required: true
      - label: APP recon
      - label: L1
      - label: L2
      
---
# SPV
- [ ] Marketing
- [ ] Group Chat
- [ ] Letter of Agreement / PKS Signed
- [ ] API Documentation & Analysis (API Doc details, flows, etc)
- [ ] Contoh struk
- [ ] Receipt Sample & Mapping (fields from API to Receipt)
- [ ] mapping response
- [ ] Network Access (opt.), [Perlu / Tidak Perlu] setting koneksi wireguard
- [ ] Dev Credential
- [ ] Sandbox Pre-Test
- [ ] Kode bin (BRI) :  #corp_code (opt)
- [ ] Cust Id Length : #nopel_length
- [ ] Modifikasi Nopel : [Ya/Tidak]

# Task
- [ ] Loket 1
- [ ] Loket 2
- [ ] Recon
