name: Update status on project board
on:
  issues:
    types: [assigned]
  pull_request:
    types: [assigned]
jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Update "Start date" field
        uses: EndBug/project-fields@v2
        with:
            operation: set
            fields: "Start date",Status
            github_token: ${{ secrets.TOKEN1 }}
            project_url: https://github.com/users/shitenmaru/projects/1
            values: "2025-09-01","Dev - In Progress"
