name : Project Automation
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed
jobs:
  my_job:
      uses: EndBug/project-fields@v2
      with:
        operation: set
        fields: "Est. Hours"
        github_token: ${{ secrets.DEV_TOKEN }}
        project_url: https://github.com/users/shitenmaru/projects/1
        values: 1
